### ISSUE TITLE
What are these magic numbers?

### ISSUE THREAD

**Issue by Tvde1** [xamarinhowto/BottomSheetModal#1]
I see a few magic number:

- openPosition is 60 for android and 20 for iOS)
- Closing the sheet translates the sheet to SheetHeight + 60

What is the meaning of this 60 and 20?

**Comment by v0xw** [comment]
Have you ever found this out @Tvde1 ?
I also need to know what this means exactly

**Comment by Tvde1** [comment]
Nope

**Comment by xamarinhowto** [comment]
These were done as part of the demo for this and worked for that specific use case. We plan to update things in the DarkIce.Toolkit and release with more documentation. Thanks for point out.
