### ISSUE TITLE
Doesn't work without BindingContext

### ISSUE THREAD

**Issue by DrunkRussianGun** [xamarinhowto/BottomSheetModal#2]
`BottomSheetControl` breaks when there is no binding context on the parent page. To reproduce, simply remove these [lines 8–10 from MainPage.xaml](https://github.com/xamarinhowto/BottomSheetModal/blob/39f4e182c951d74530e3e53d71e41be46c8f3f3c/BottomSheet/MainPage.xaml#L8-L10):

```xml
<ContentPage.BindingContext>
    <viewmodel:MainViewModel/>
</ContentPage.BindingContext>
```

**Comment by xamarinhowto** [comment]
This is only intended for a MVVM approach, as most projects use this pattern as standard.
